# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  licencse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@@v1.0.0
      - uses: jonabc/setup-licensed@v1
        with:
          version: 2.x
      - run: npm install # install your projects dependencies in local environment
      - id: licensed
        uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}